version: '3.9'
services:
  nest:
    container_name: nest-back
    image: server-dev:1.0.0
    build:
      target: development
      dockerfile: apps/src-BE/Dockerfile
    command: turbo run start --scope='@nesting/src-be'
    ports:
      - ${PORT}:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app/BE
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_URI_NO_AUTH: ${DATABASE_URI_NO_AUTH}
      DATABASE_URI: ${DATABASE_URI}
      DATABASE_PORT: ${DATABASE_PORT}
    healthcheck:
      test: echo 'curl localhost:${PORT}/'
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  remix:
    container_name: remix-front
    image: remix-front:1.0.0
    build:
      target: development
      dockerfile: ./apps/src-FE/Dockerfile
    command: turbo run start --scope='@nesting/src-fe'
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app/FE
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
    healthcheck:
      test: echo 'curl localhost:8080/'
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: server-mongodb
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${DATABASE_URI} --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
